site_name: Rusty Buddy Documentation
site_url: https://docs.rusty-buddy.org
site_description: A comprehensive guide to Rusty Buddy, an AI-powered command-line tool for developers.

# Define the theme for the documentation
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme)"
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: brown
      accent: deep orange
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: brown
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Enable plugins, if needed
plugins:
  - search  # Enables full-text search within the documentation
  - social:
      cards_layout_options:
        font_family: "Source Code Pro"

# Navigation structure for the documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - Configuration Guide: configuration.md
  - Commands:
      - Overview: commands.md
  - Personas: personas.md
  - Usecases:
      - Knowledge is Power: usecases/using_knowledge_feature.md
      - Start for Free: usecases/start_for_free.md
      - Case study Rust development: usecases/case_study_rust.md
      - Assisted Debugging: usecases/assisted_debugging.md
      - Code Refactoring: usecases/code_refactoring.md
      - Dynamic Configuration Automation: usecases/dynamic_config_automation.md
      - Security Audit: usecases/security_audit.md
      - Test Case Development: usecases/test_cases.md
      - Writing Documentation: usecases/write_documentation.md

# Additional configuration settings
markdown_extensions:
  - toc:
      permalink: true  # Adds a permalink to each heading in the table of contents
  - tables
  - fenced_code
  - footnotes
  - codehilite:
      use_pygments: False
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Include any additional files or settings required for deployment or functionality
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hg8496/rusty-buddy
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/RustyBuddy_org
  # etc...

# Provide options for deploying the site if using features like GitHub Pages
# use_directory_urls: false  # Set to false if linking pages with file extensions
