name: Build CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu  # Linux ARM 64-bit                                                        
          - armv7-unknown-linux-gnueabihf  # Linux ARM 32-bit                                                    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rusty-buddy-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/rusty-buddy${{ matrix.os == 'windows-latest' && '.exe' || '' }}
