name: Build CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        config:
          - os: ubuntu-20.04
            rust_target: x86_64-unknown-linux-gnu
            ext: ''
            args: ''
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            ext: ''
            args: ''
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            ext: ''
            args: ''
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
            ext: '.exe'
            args: ''
          - os: windows-latest
            rust_target: aarch64-pc-windows-msvc
            ext: '.exe'
            args: '--no-default-features --features native-tls-vendored'
            
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Build
        run: cargo build --release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rusty-buddy-${{ matrix.config.target }}
          path: target/release/rusty-buddy${{ matrix.config.os == 'windows-latest' && '.exe' || '' }}
